### ISSUE TITLE
CW v1.6.0 / v.1.6.1 interfering with Skytils

### ISSUE THREAD

**Issue by LunaFall** [Ninjune/coleweight#1]
For some reason, both of these mods don't work together (v1.5.5 did work properly), map won't show and Skytils waypoints won't work either. 

This is a Crystal Hollows lobby with CW and Skytils. Map doesn't show up at all, neither will any CH feature.
![n6HUCIV](https://user-images.githubusercontent.com/41271741/202703705-5c4fe85d-9f62-4cc9-884f-0ffea7e5ebb6.png)

As soon as I delete Coleweight, every CH feature works again, map and waypoints.
![image](https://user-images.githubusercontent.com/41271741/202703947-68745ca3-0965-4a80-aa49-2289a56b3722.png)

**Comment by Ninjune** [comment]
I am unable to recreate this bug with the provided information. It seems to be an issue of Skytils not detecting that the player is in the crystal hollows, but the Coleweight module shouldn't affect that. Please respond with your Skytils version as well as if you can still recreate it.
