### ISSUE TITLE
Printing the letter "b" while mining

### ISSUE THREAD

**Issue by tbusanny** [Ninjune/coleweight#15]
Hi there,
My son was curious why a "b" appears when he finds a "Pristine Gem" in the game. I looked into it and found the following code snippet. I'm not sure if this behavior is intentional, but I wanted to bring it to your attention.

Have a great weekend and thanks in advance!

Snippet:
https://github.com/Ninjune/coleweight/blob/d3b0d4e0ef688ef9fb9e5c927521f082dc2b3679/render/guis/coinGui.js#L24

**Comment by Ninjune** [comment]
I left the debug message I was using to test if the regex worked. Fixed in next update.
