### ISSUE TITLE
Cannot get Coleweight to work with ChatTriggers

### ISSUE THREAD

**Issue by HammerheadH** [Ninjune/coleweight#17]
I am using 1.8.9 Forge with ct v2.2.0, cw v1.13.3
ChatTriggers seems to be working fine, when I run the command /ct import ColeWeight I get told I am unable to import Coleweight. In the ct console it says:
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
along with some other jargon.
So I installed it manually along with the other required modules. I do /ct load, it detects cw and lists it properly in /ct modules, however when I run a /cw command I get the same error message as above with no in game responce. It seems to be having issues with the SSL certificate however I don't know where to go from here. Thanks

**Comment by Ninjune** [comment]
https://github.com/ChatTriggers/ChatTriggers/wiki/Fixing-broken-imports
